# Created using wingetcreate 1.2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: NicholasHTollerVey.MuEditor
PackageVersion: 1.2.0
Installers:
- InstallerUrl: https://github.com/mu-editor/mu/releases/download/v1.2.0/MuEditor-win64-1.2.0.msi
  InstallerLocale: en-US
  Architecture: x64
  InstallerType: wix
  InstallerSha256: 8BEF34673998CA5644F9D222FC4A13E24A64023A72940E685BCEC27827CD765E
  ProductCode: '{BC808DD4-82A7-43D9-898A-4A2CD16C81AA}'
ManifestType: installer
ManifestVersion: 1.4.0
