# Created using wingetcreate 1.2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: NicholasHTollerVey.MuEditor
PackageVersion: 1.2.0
PackageLocale: en-US
Publisher: Nicholas H.Tollervey
PackageName: Mu Editor
License: GPL-3.0
ShortDescription: Mu is a Python code editor for beginner programmers based on extensive feedback given by teachers and learners.
ManifestType: defaultLocale
ManifestVersion: 1.4.0
