# Created using wingetcreate 1.2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: Autodesk.Meshmixer
PackageVersion: 11.5.474
Installers:
- InstallerUrl: https://meshmixer.com/downloads/Autodesk_Meshmixer_v3p5_Win64.exe
  Architecture: x64
  InstallerType: nullsoft
  InstallerSha256: 5D08CB6254E4D4280137D6D37EC689FC3F0C61DAD08BBC978A451AC16B7F271C
  InstallerSuccessCodes:
  - 1223 # https://forums.autodesk.com/t5/installation-licensing/it-admin-cannot-install-except-manually/m-p/8865579#M224430
ManifestType: installer
ManifestVersion: 1.4.0
