# Created with YamlCreate.ps1 v2.2.13 $debug=NVS0.CRLF.7-4-0.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: DassaultSystemes.Draftsight
PackageVersion: 24.0.0.5001
InstallerType: exe
InstallerSwitches:
  Silent: /Q /C:"setup.exe /S /v""LICENSETYPE=0 /qn"""
  SilentWithProgress: /Q /C:"setup.exe /S /v""LICENSETYPE=0 /qb"""
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: http://www.draftsight.com/download-windows64
  InstallerSha256: 63C3C58B706197C8F9FED295B28F531974FC8022468CFA2D42997592A7ED2320
ManifestType: installer
ManifestVersion: 1.5.0
